browser:
  language: en
  visible: true
  geolocation: US
  proxy: ""

search:
  type: desktop

urls:
  - name: youtube
    url: "https://www.youtube.com/watch?v=example_video_id"  # Replace with your desired YouTube URL
    duration: 5
    youtube: true  # Enable YouTube-specific functionality
  - name: example
    url: "https://www.example.com"
    duration: 3
    youtube: false  # Disable YouTube-specific functionality

discord_webhook_url: "discord://your_discord_webhook_url"

logging:
  level: DEBUG
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
